# Generated by Django 4.1.3 on 2022-11-25 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_roles_updated_at_alter_userroles_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roles',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
