# Generated by Django 4.1.3 on 2022-12-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_roles_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
