# Generated by Django 4.1.3 on 2023-02-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_roles_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='updated_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
