# Generated by Django 4.1.3 on 2023-02-01 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidateApplicationSubmition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('isSent', models.BooleanField(default=False)),
                ('created_by', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.DateTimeField(auto_now=True)),
                ('candidateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidateApplicationSubmition.candidateappsubmit')),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_consultant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Consult',
            },
        ),
    ]
