# Generated by Django 4.1.3 on 2023-02-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerJobs', '0006_alter_companyinformation_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
