# Generated by Django 4.1.3 on 2023-02-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerJobs', '0007_alter_departments_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjobs',
            name='job_status',
            field=models.BooleanField(default=False),
        ),
    ]
