# Generated by Django 4.1.3 on 2023-02-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerJobs', '0008_careerjobs_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerjobs',
            name='jobStatus',
        ),
    ]
