# Generated by Django 4.1.3 on 2023-02-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerJobs', '0009_remove_careerjobs_jobstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerjobs',
            old_name='job_status',
            new_name='jobStatus',
        ),
    ]
