# Generated by Django 4.1.3 on 2023-03-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerJobs', '0010_rename_job_status_careerjobs_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerjobs',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
