# Generated by Django 4.1.3 on 2023-03-01 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerJobs', '0011_careerjobs_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerjobs',
            name='jobStatus',
        ),
        migrations.AlterField(
            model_name='careerjobs',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
