# Generated by Django 4.1.3 on 2023-03-01 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careerJobs', '0013_careerjobs_jobstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='careerjobs',
            old_name='jobStatus',
            new_name='job_status',
        ),
    ]
