# Generated by Django 4.1.3 on 2023-02-03 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApplicationSubmition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatecertificates',
            name='candidateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateCertificates', to='candidateApplicationSubmition.candidateappsubmit'),
        ),
        migrations.AlterField(
            model_name='candidateeducations',
            name='candidateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateEducation', to='candidateApplicationSubmition.candidateappsubmit'),
        ),
        migrations.AlterField(
            model_name='candidateexperience',
            name='candidateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidateExperience', to='candidateApplicationSubmition.candidateappsubmit'),
        ),
        migrations.AlterField(
            model_name='candidaterelatedjob',
            name='canidateId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidateApplicationSubmition.candidateappsubmit'),
        ),
    ]
