# Generated by Django 4.1.3 on 2023-02-07 06:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('careerJobs', '0004_alter_factors_isactive'),
        ('candidateApplicationSubmition', '0003_candidateevaluation_delete_candidatequalification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateevaluation',
            name='candidateRelatedJob',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidateApplicationSubmition.candidaterelatedjob'),
        ),
        migrations.CreateModel(
            name='FactorAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answerOfQues', models.CharField(max_length=200)),
                ('score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('candidateEvaluationId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidateApplicationSubmition.candidateevaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerJobs.factors')),
            ],
        ),
    ]
