# Generated by Django 4.1.3 on 2023-02-07 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApplicationSubmition', '0004_alter_candidateevaluation_candidaterelatedjob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateevaluation',
            name='overAllScore',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
