# Generated by Django 4.1.3 on 2023-02-07 06:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApplicationSubmition', '0005_alter_candidateevaluation_overallscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateevaluation',
            name='fromDate',
        ),
        migrations.RemoveField(
            model_name='candidateevaluation',
            name='toDate',
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateevaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
