# Generated by Django 4.1.3 on 2023-02-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApplicationSubmition', '0006_remove_candidateevaluation_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateeducations',
            name='institutionName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
