# Generated by Django 4.1.3 on 2023-04-10 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApplicationSubmition', '0008_alter_candidatecertificates_candidateid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateappsubmit',
            old_name='uploadResume',
            new_name='profileImage',
        ),
        migrations.AddField(
            model_name='candidateappsubmit',
            name='professionalSummry',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
