# Generated by Django 4.1.3 on 2023-04-10 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApplicationSubmition', '0009_rename_uploadresume_candidateappsubmit_profileimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateappsubmit',
            old_name='professionalSummry',
            new_name='professionalSummary',
        ),
    ]
