# Generated by Django 4.1.3 on 2023-04-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidateApplicationSubmition', '0011_alter_candidateappsubmit_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateappsubmit',
            name='profileImage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
