# Generated by Django 4.1.3 on 2022-11-18 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDropCv',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('linkedInUrl', models.CharField(max_length=2000)),
                ('socialUrl', models.CharField(max_length=2000)),
                ('resumeUpload', models.CharField(max_length=200)),
                ('coverLetter', models.CharField(max_length=200)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
